# Generated by Django 3.0.5 on 2020-04-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapp', '0002_raster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raster',
        ),
    ]
