# Generated by Django 2.2.5 on 2020-04-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapp', '0002_raster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raster',
        ),
    ]
